### ISSUE TITLE
Constants and Variables

### ISSUE THREAD

**Issue by hvetsa** [vvetsa/learning-java#2]
- [x] What is a constant in Java
- [x] What is a variable in Java
- [x] List basic types of variables
- [x] Declare two variables of type Integer, add them and print the answer
- [x] Declare two variables of type String, join them end print them

**Comment by vvetsa** [comment]
a constant in java is a variable with a clue that does not change

a variable in java holds values that can be changed

basic types of variables include integers, floats, strings, and booleans
