### ISSUE TITLE
converting data types

### ISSUE THREAD

**Issue by hvetsa** [vvetsa/learning-java#3]
1. Create a string variable,assign the value "1". create another variable of integer type with value 2. 
-- show the code snippet that adds the varilables and print 3.

2. Explain converting data types from one to another and explain its limitations and uses.

3. Explain difference between Float and Double.

4. What happens if an integer is compared with double (eg: 1 == 1.0 )?

5. Explain different parts of the "if" statement.

6. What are different "if" statement construction?

**Comment by vvetsa** [comment]
1) see code

2) one can convert from one data type to another using the .valueOf(); command and it is used to make many variables the same type but can only be converted to a type when it meets certain criteria, for example string "10a" cannot be made an int

3) float is 32 bits (7 digits) while double is 64 bits (15-16 digits)

4) true 

5) if( condition ){ statements }

6) common ones include
if
if - else
if - else if
if - else if - else
